# review_report_url: https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-249a
# review_date: 2024-10-07
# review_author: Blackpearl
# review_rule_useful: true
# review_rule_classification: proceed to testing
# review_rule_classification_reason: na
# review_rule_ttp_match: yes
# review_notes:
#  - This Sigma rule detects potentially malicious web requests aimed at dumping configuration settings and credentials from IP cameras by exploiting default usernames and passwords. It monitors specific URL patterns used in commands that target vulnerable endpoints like PictureCatch.cgi and ssi.cgi to extract sensitive data. False positives may occur if legitimate administrative access involves similar configuration activities.

title: Dumping Configuration Settings and Credentials via Web Requests
id: 5457f507-df79-406d-9c2d-5fa8e8305782
status: experimental
description: Detects web requests that are likely intended to dump configuration settings and credentials by exploiting default usernames and passwords in IP cameras and executing remote commands.
references:
  - https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-249a
author: System Two Security
date: 2024/10/03
tags:
  - attack.reconnaissance
logsource:
  category: application
  product: modsecurity
detection:
  selection1:
    RequestURL|contains|all:
      - key=PWNED
      - data_type=1
      - secret=1
      - /PictureCatch.cgi?username=
      - '&password=%3becho%20%22%3c%21--%23include%20file=%22SYS_CFG%22--%3e%22%3etmp/Login.htm%3b&'
      - channel=1
      - attachment=1
  selection2:
    RequestURL|contains: /ssi.cgi/tmp/Login.htm
  condition: selection1 or selection2
falsepositives:
  - Legitimate administrative activity that involves accessing camera configuration settings or credentials.
level: high
