# review_report_url: https://www.zscaler.com/blogs/security-research/moonwalk-deep-dive-updated-arsenal-apt41-part-2
# review_date: 2024-11-03
# review_author: Blackpearl
# review_rule_useful: true
# review_rule_classification: proceed to testing
# review_rule_classification_reason: na
# review_rule_ttp_match: yes
# review_notes:
#  - This Sigma rule is used for identifying accesses to the MoonWalk malware configurations files which are found in C:\ProgramData\ and have the extension .config. The rule triggers on suspicious events of file that could show the launch or modification of configuration files related to any type of malware.
title: Detection of MoonWalk Malware Configuration File Access
id: f894788f-bad8-4e8c-a776-b3ec4f9d9b51
status: experimental
description: Detects the access to a specific configuration file used by the MoonWalk malware, which is located in C:\ProgramData\ and named after the MD5 hash of a certain byte sequence from the malware configuration.
references:
  - https://www.zscaler.com/blogs/security-research/moonwalk-deep-dive-updated-arsenal-apt41-part-2
author: System Two Security
date: 2024/08/22
tags:
  - attack.execution
logsource:
  product: windows
  category: file_event
detection:
  selection:
    TargetFilename|startswith: C:\ProgramData\
    TargetFilename|endswith: .config
  condition: selection
falsepositives:
  - Legitimate applications that store configuration files in C:\ProgramData\ with a .config extension
level: high
