# review_report_url: https://hunt.io/blog/latrodectus-malware-masquerades-as-ahnlab-security-software-to-infect-victims
# review_date: 2024-11-07
# review_author: Blackpearl
# review_rule_useful: true
# review_rule_classification: proceed to testing
# review_rule_classification_reason: na
# review_rule_ttp_match: yes
# review_notes:
#  - This Sigma rule is designed to detect the loading of a specific malicious DLL, "MeDExt.dll," used in the Latrodectus malware campaign, which impersonates the legitimate MeD Engine Extension from AhnLab Smart Defense. It checks for the loading of this DLL file or verifies its hash within Windows image load events. The rule is flagged with a high severity level due to the risk posed by this malware. False positives may occur if legitimate software updates modify the original DLL, resulting in a file with the same name but a different hash.
title: Detection of Latrodectus Malware Masquerading as AhnLab Security Software
id: ffc006ea-07e0-439f-b00e-03f445d1f963
status: experimental
description: Detects the presence of a specific malicious DLL file associated with the Latrodectus malware campaign, which mimics the legitimate MeD Engine Extension from AhnLab Smart Defense.
references:
  - https://hunt.io/blog/latrodectus-malware-masquerades-as-ahnlab-security-software-to-infect-victims
author: System Two Security
date: 2024/09/04
tags:
  - attack.persistence
logsource:
  product: windows
  category: image_load
detection:
  selection:
    ImageLoaded|endswith: \MeDExt.dll
    Hashes|contains: SHA256:23546ec6747ed6788a14c9410f3fc458b5cff8bd13885100bf48e3930a0bdf
  condition: selection
falsepositives:
  - Legitimate software updates or modifications to the legitimate MeD Engine Extension DLL that coincidentally have the same file name but different hash values.
level: high
