# review_report_url: https://blog.sekoia.io/a-glimpse-into-the-quad7-operators-next-moves-and-associated-botnets/
# review_date: 2024-10-07
# review_author: Blackpearl
# review_rule_useful: true
# review_rule_classification: proceed to testing
# review_rule_classification_reason: na
# review_rule_ttp_match: yes
# review_notes:
#  - This Sigma rule detects the configuration of firewall rules on Linux systems that permit traffic on UDP port 9999 and a range of TCP and UDP ports from 10000 to 40000. These modifications are indicative of potential activity associated with the Quad7 FsyNet botnet. The rule monitors audit logs for commands involving firewall-cmd that include specific arguments related to these ports.

title: Detection of Quad7 FsyNet Botnet Firewall Rule Configuration
id: fc8b3235-5180-490d-a99a-4cf6a9245a03
status: experimental
description: Detects the setup of firewall rules to allow traffic on UDP port 9999 and a range of TCP and UDP ports from 10000 to 40000, which is indicative of the Quad7 FsyNet botnet activity.
references:
  - https://blog.sekoia.io/a-glimpse-into-the-quad7-operators-next-moves-and-associated-botnets
author: System Two Security
date: 2024/10/03
tags:
  - attack.command-and-control
logsource:
  product: linux
  service: auditd
detection:
  selection:
    a0|contains|all:
      - --permanent
      - firewall-cmd
      - --add-port=9999/udp
    a1|contains|all:
      - --permanent
      - --add-port=10000-40000/tcp
      - firewall-cmd
    a2|contains|all:
      - --add-port=10000-40000/udp
      - --permanent
      - firewall-cmd
  condition: selection
falsepositives:
  - Legitimate firewall rule changes by system administrators for non-malicious purposes.
level: high
